//! The Alto's 16-task wakeup arbiter as a [`rhdl_rule`] kernel.
//!
//! ## The Alto's task system, per the *Alto Hardware Manual* §4
//!
//! The Alto microengine is shared by **16 hardware tasks** taking
//! turns one cycle at a time.  Each task has:
//!
//! - its own **MPC** (microprogram counter, 10 bits)
//! - a **wakeup signal** (driven by hardware: disk, display, mouse,
//!   etc.)
//! - a fixed **priority** (Task 15 highest, Task 0 lowest)
//!
//! Each cycle the hardware looks at the 16 wakeup signals, picks
//! the highest-priority woken task, and runs one microinstruction
//! from that task's MPC.  All 16 tasks share the universal
//! microengine state — T, L, R-registers, M-channel — but each
//! has its own MPC.
//!
//! ## Why this is the canonical [`rhdl_rule`] use case
//!
//! In Bluespec System Verilog, each Alto task is naturally written
//! as a `rule` with a `when` clause.  The 16 rules are mutually
//! exclusive by construction (they share write-state); the BSV
//! scheduler picks at most one per cycle, the highest-priority
//! one whose guard is true.
//!
//! [`rhdl_rule`] expresses this directly via `#[rule_kernel_attr]`
//! on the impl block plus `#[rule(priority = N)]` annotations —
//! the same shape a BSV programmer would write.  No bespoke
//! priority encoder, no hand-written wakeup mux, no manual
//! task-select state machine: the scheduler is generated by
//! [`rhdl_rule`] from the rule annotations alone.
//!
//! ## What's in Phase 2 (this module)
//!
//! [`AltoTaskSystem`] — a 16-task widget with:
//!
//! - 16 per-task MPCs ([`Bits<10>`])
//! - a `last_task` DFF (visible for trace / observability)
//! - a `current_task` output that downstream widgets (like the
//!   microengine) consume to know which task is running this cycle
//!
//! Each task is one [`rhdl_rule`] `#[rule]` method, guarded by its
//! wakeup signal, with body that:
//!
//! 1. Reads the task's current MPC.
//! 2. Bumps it by the runtime-supplied `next_mpc` (so the parent
//!    can compute the next-MPC via the microengine's `compute_cycle`
//!    and pass it back).
//! 3. Records `last_task = its index`.
//!
//! This module is the **task arbiter** — pure priority arbitration
//! over 16 firable rules, with per-task MPC management.  The actual
//! per-cycle microinstruction execution (ALU, T-load, L-load,
//! R-writes) is delegated to [`crate::microengine::Microengine`]
//! composed alongside.
//!
//! Phase 3 will diverge the per-task bodies for the I/O-specific
//! tasks (Disk fetches a per-word DMA; Display loads pixels into
//! the framebuffer; etc.), at which point the Alto task system
//! becomes a true rhdl-rule showcase: 16 tasks, 16 rule bodies,
//! each specialised for its hardware role.

use rhdl::prelude::*;
use rhdl_fpga::core::dff;
use rhdl_rule::rule_kernel_attr;

/// Inputs to the task system.
#[derive(PartialEq, Debug, Digital, Clone, Copy, Default)]
pub struct AltoIn {
    /// 16-bit wakeup vector.  Bit i = 1 means task i wants to run.
    /// Driven by the platform: disk-controller asserts bit 1/2;
    /// display-controller asserts bit 5; mouse asserts bit 10; etc.
    pub wakeups: Bits<16>,
    /// Per-task next-MPC values, computed by the parent (typically
    /// from the microengine's `compute_cycle` applied to each
    /// task's microinstruction).  The winning task's slot is
    /// committed; the others are ignored.
    pub next_mpc_per_task: [Bits<10>; 16],
}

/// Outputs from the task system.
#[derive(PartialEq, Debug, Digital, Clone, Copy, Default)]
pub struct AltoOut {
    /// The 16 per-task MPCs (visible for debug / lockstep).
    pub task_mpc: [Bits<10>; 16],
    /// Index of the task that ran *last* cycle (committed at edge).
    pub last_task: Bits<4>,
    /// True iff at least one wakeup bit is set this cycle and a
    /// rule will (or did) fire.  When false, the engine is idle.
    pub any_running: bool,
    /// Number of times Task 1 (Disk Sector) has fired since reset.
    /// Phase-3 specialization marker — proves the task body diverged.
    pub disk_sector_count: Bits<16>,
    /// Number of times Task 2 (Disk Word) has fired since reset.
    /// Phase-3 specialization marker — proves the task body diverged.
    pub disk_word_count: Bits<16>,
}

/// The Alto task system: 16 priority-ordered hardware tasks
/// sharing one microengine.
///
/// Each `#[rule]` in the impl below corresponds to one Alto
/// hardware task.  Rules are listed in **descending priority
/// order** (Task 15 first → fires first when multiple are
/// guarded-true).  This matches the Alto's hardware priority
/// (high task number = high priority), and the BSV idiom of
/// "earlier-written rule wins."
#[derive(Clone, Debug, Default, Synchronous, SynchronousDQ)]
pub struct AltoTaskSystem {
    /// Per-task MPC (16 × 10 bits).
    pub task_mpc: dff::DFF<[Bits<10>; 16]>,
    /// Last task that fired (records the priority arbiter's choice
    /// from the previous cycle).
    pub last_task: dff::DFF<Bits<4>>,
    /// Latched "any task fired last cycle" — true when at least one
    /// of the 16 rules fired.  Used for observability + tests.
    pub any_running: dff::DFF<bool>,
    /// Phase-3: Disk Sector task fire counter.  Only Task 1's body
    /// updates this — proves the rule body diverged from the others.
    pub disk_sector_count: dff::DFF<Bits<16>>,
    /// Phase-3: Disk Word task fire counter.  Only Task 2's body
    /// updates this — proves the rule body diverged from the others.
    pub disk_word_count: dff::DFF<Bits<16>>,
}

#[rule_kernel_attr]
impl AltoTaskSystem {
    // ---- Task 15 (highest priority) ---------------------------------
    #[rule(priority = 0)]
    fn task_15(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x8000)) != bits::<16>(0));
        let task = bits::<4>(15);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 14 ----------------------------------------------------
    #[rule(priority = 1)]
    fn task_14(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x4000)) != bits::<16>(0));
        let task = bits::<4>(14);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 13 ----------------------------------------------------
    #[rule(priority = 2)]
    fn task_13(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x2000)) != bits::<16>(0));
        let task = bits::<4>(13);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 12 ----------------------------------------------------
    #[rule(priority = 3)]
    fn task_12(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x1000)) != bits::<16>(0));
        let task = bits::<4>(12);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 11 ----------------------------------------------------
    #[rule(priority = 4)]
    fn task_11(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0800)) != bits::<16>(0));
        let task = bits::<4>(11);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 10 — Mouse --------------------------------------------
    #[rule(priority = 5)]
    fn task_10_mouse(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0400)) != bits::<16>(0));
        let task = bits::<4>(10);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 9 — BLT (Memory Block Move) ---------------------------
    #[rule(priority = 6)]
    fn task_9_blt(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0200)) != bits::<16>(0));
        let task = bits::<4>(9);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 8 — Cursor --------------------------------------------
    #[rule(priority = 7)]
    fn task_8_cursor(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0100)) != bits::<16>(0));
        let task = bits::<4>(8);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 7 — Display Vertical ----------------------------------
    #[rule(priority = 8)]
    fn task_7_display_vertical(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0080)) != bits::<16>(0));
        let task = bits::<4>(7);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 6 — Display Horizontal --------------------------------
    #[rule(priority = 9)]
    fn task_6_display_horizontal(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0040)) != bits::<16>(0));
        let task = bits::<4>(6);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 5 — Display Word --------------------------------------
    #[rule(priority = 10)]
    fn task_5_display_word(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0020)) != bits::<16>(0));
        let task = bits::<4>(5);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 4 — Memory Refresh (no-op on FPGA BRAM) ---------------
    #[rule(priority = 11)]
    fn task_4_memory_refresh(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0010)) != bits::<16>(0));
        let task = bits::<4>(4);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 3 — Ethernet ------------------------------------------
    #[rule(priority = 12)]
    fn task_3_ethernet(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0008)) != bits::<16>(0));
        let task = bits::<4>(3);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    // ---- Task 2 — Disk Word -----------------------------------------
    //
    // Phase-3 specialization: in addition to bumping the per-task MPC,
    // this rule increments `disk_word_count`.  Every Disk Word fire
    // corresponds to one word transferred between memory and the disk
    // sector buffer (DMA per word).  In Phase 3.5 this body will also
    // drive the Memory + DiabloDisk sub-widgets directly.
    #[rule(priority = 13)]
    fn task_2_disk_word(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0004)) != bits::<16>(0));
        let task = bits::<4>(2);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
        // Phase-3 divergence: bump the word-transfer counter.
        ctx.disk_word_count = *ctx.disk_word_count + bits::<16>(1);
    }

    // ---- Task 1 — Disk Sector ---------------------------------------
    //
    // Phase-3 specialization: in addition to bumping the per-task MPC,
    // this rule increments `disk_sector_count`.  Every Disk Sector
    // fire corresponds to one sector boundary on the spinning disk
    // (the rotational tick).  In Phase 3.5 this body will also program
    // the DiskController KADR / KCOM registers and arm a transfer.
    #[rule(priority = 14)]
    fn task_1_disk_sector(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0002)) != bits::<16>(0));
        let task = bits::<4>(1);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
        // Phase-3 divergence: bump the sector-boundary counter.
        ctx.disk_sector_count = *ctx.disk_sector_count + bits::<16>(1);
    }

    // ---- Task 0 — Emulator (lowest priority — runs by default) ------
    //
    // The Emulator task is the Alto's "default" — it runs whenever
    // no higher-priority task is woken.  In real Alto hardware,
    // Task 0's wakeup is hardwired-true; here we model it as a
    // regular wakeup-bit that the platform leaves asserted.
    //
    // Per the Alto Hardware Manual: "Task 0 (Emulator) is the
    // default task ... it has no wakeup signal of its own;
    // hardware ensures it runs when no other task is requesting
    // the engine."
    #[rule(priority = 15)]
    fn task_0_emulator(ctx: &mut RuleCtx<Self>, i: AltoIn) {
        guard!((i.wakeups & bits::<16>(0x0001)) != bits::<16>(0));
        let task = bits::<4>(0);
        let mut new_mpcs = *ctx.task_mpc;
        new_mpcs[task] = i.next_mpc_per_task[task];
        ctx.task_mpc = new_mpcs;
        ctx.last_task = task;
        ctx.any_running = true;
    }

    /// Output: visible task-system state for trace + tests.
    #[output]
    fn output(self_q: &Self, _i: AltoIn) -> AltoOut {
        AltoOut {
            task_mpc: *self_q.task_mpc,
            last_task: *self_q.last_task,
            any_running: *self_q.any_running,
            disk_sector_count: *self_q.disk_sector_count,
            disk_word_count: *self_q.disk_word_count,
        }
    }
}
