[package]
name = "rhdl-rule-core"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "Implementation of the rhdl-rule proc-macros (Phase 0)."
homepage = "https://rhdl.org"
repository = "https://github.com/samitbasu/rhdl"
keywords = ["fpga", "hdl", "hardware", "rules", "macro"]

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = { version = "2.0.106", features = ["full", "extra-traits", "visit-mut"] }
