#![warn(missing_docs)]
//! The delay-budget table the book chapter is built from.
//!
//! Generated rather than written, because the numbers in a paragraph
//! drift the moment the maths behind them changes and nothing notices.
//! The example `cic_delay_budget` writes the table into the book, and
//! `tests::the_committed_table_is_current` fails if the committed copy
//! and the current maths disagree.
//!
//! The rows are *hand-specified shapes*, not designer output. A chapter
//! about where delay comes from wants shapes the reader can see, and the
//! designer's search at these rates takes minutes.

use rhdl_dsp_design::cic::delay::{
    Breakdown, decimation_chain_breakdown, interpolation_chain_breakdown, loop_bandwidth_hz,
    seconds,
};

/// Where the committed copy lives, relative to the repository root.
pub const PATH: &str = "doc/book/src/dsp/cic_delay_budget.md";

/// The converter rate every row is referred to.
const FS: f64 = 125e6;

/// One row: a named configuration and its breakdown.
struct Row {
    what: &'static str,
    b: Breakdown,
}

fn rows() -> Vec<Row> {
    // Receive, 125 Msps down to 100 ksps. Two ways of reaching the same
    // rate change, and the same chain implemented in software.
    let one_stage = [(3usize, 1250usize, 1usize)];
    let split = [(3usize, 10usize, 1usize), (2, 25, 1), (2, 5, 1)];
    vec![
        Row {
            what: "RX, one stage R=1250 N=3, 15-tap compensator, fabric",
            b: decimation_chain_breakdown(&one_stage, 15, true),
        },
        Row {
            what: "RX, one stage R=1250 N=3, 15-tap compensator, software",
            b: decimation_chain_breakdown(&one_stage, 15, false),
        },
        Row {
            what: "RX, split 10x25x5 N=3,2,2, 3-tap compensator, fabric",
            b: decimation_chain_breakdown(&split, 3, true),
        },
        Row {
            what: "RX, split 10x25x5 N=3,2,2, 3-tap compensator, software",
            b: decimation_chain_breakdown(&split, 3, false),
        },
        Row {
            what: "TX, one stage R=125 N=3, 15-tap compensator, fabric",
            b: interpolation_chain_breakdown(&[(3, 125, 1)], 15, true),
        },
        Row {
            what: "TX, split 5x25 N=5,2, 21-tap compensator, fabric",
            b: interpolation_chain_breakdown(&[(5, 5, 1), (2, 25, 1)], 21, true),
        },
    ]
}

/// The table, as GitHub-flavoured markdown.
pub fn budget_markdown() -> String {
    let mut s = String::new();
    s.push_str(
        "<!-- Generated by `cargo run --example cic_delay_budget --package rhdl-fpga`. -->\n",
    );
    s.push_str("<!-- Do not edit by hand; `doc::delay_budget` has a test that checks it. -->\n\n");
    s.push_str("| configuration | cascade | int pipe | comb pipe | out reg | comp | total | µs | loop BW |\n");
    s.push_str("|---|---:|---:|---:|---:|---:|---:|---:|---:|\n");
    for Row { what, b } in rows() {
        s.push_str(&format!(
            "| {} | {:.0} | {:.0} | {:.0} | {:.0} | {:.0} | {:.0} | {:.1} | {:.1} kHz |\n",
            what,
            b.cic_body,
            b.integrator_pipeline,
            b.comb_pipeline,
            b.output_registers,
            b.compensator,
            b.total(),
            seconds(b.total(), FS) * 1e6,
            loop_bandwidth_hz(b.total(), FS) / 1e3,
        ));
    }
    s.push_str(
        "\nSamples are referred to the chain's input rate for RX and to the converter rate for\n\
         TX, both 125 Msps. `loop BW` is the `1/(10·delay)` rule of thumb and nothing more.\n",
    );
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn committed() -> String {
        let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .join(PATH);
        std::fs::read_to_string(root).expect("the committed table must exist")
    }

    /// **The committed table matches the current maths.**
    ///
    /// The whole point of generating it. Re-run
    /// `cargo run --example cic_delay_budget --package rhdl-fpga` and
    /// audit the diff.
    #[test]
    fn the_committed_table_is_current() {
        assert_eq!(committed(), budget_markdown());
    }

    /// **The table shows the pipelining costing more than the
    /// compensator in the split configuration, and less in the
    /// single-stage one.**
    ///
    /// This is the chapter's whole argument, so it is asserted here
    /// rather than left to the reader to notice.
    #[test]
    fn the_table_shows_the_ordering_reversing() {
        let r = rows();
        let single = &r[0].b;
        let split = &r[2].b;
        assert!(
            single.compensator > single.comb_pipeline,
            "single stage: {single:?}"
        );
        assert!(split.comb_pipeline > split.compensator, "split: {split:?}");
    }

    /// **A software implementation of the same chain is shorter**, by
    /// exactly the pipelining, which is the fabric-versus-ARM figure.
    #[test]
    fn software_is_shorter_by_exactly_the_pipelining() {
        let r = rows();
        for (fabric, software) in [(&r[0].b, &r[1].b), (&r[2].b, &r[3].b)] {
            assert_eq!(software.comb_pipeline, 0.0);
            assert_eq!(
                fabric.total() - software.total(),
                fabric.comb_pipeline,
                "fabric {fabric:?} software {software:?}"
            );
        }
        // And in the split case it is the largest single term -- a
        // third of the loop's delay spent on a register nobody chose.
        assert_eq!(r[2].b.dominant().0, "comb pipeline", "{:?}", r[2].b);
        assert!(r[2].b.comb_pipeline / r[2].b.total() > 0.3);
    }
}
