//! Turn the checked-in primitive libraries into Rust `const` declarations.
//!
//! # Why a build script rather than reading the file at run time
//!
//! RHDL does its compilation at run time: descriptors are built when the
//! program runs. A path held in a descriptor would therefore be resolved
//! relative to the working directory of whatever binary called
//! `descriptor()` — a test, an example, a synthesis driver — and a
//! missing or stale file would surface as a runtime error from deep
//! inside descriptor construction, which is the worst place for it.
//!
//! Read here instead, a malformed library is a build failure that names
//! the offending module, and the generated code is ordinary Rust that the
//! compiler checks.
//!
//! # Why no shared serde types
//!
//! `black-box-connectivity.md` §9 asked where the serde types should live,
//! since a build script cannot depend on the crate it is building —
//! proposing either a new leaf crate or duplicated definitions with a
//! test asserting they agree.
//!
//! Neither is needed. This script deserialises into its own private
//! structs and emits *text*; the text names the runtime types. Agreement
//! between the two is checked by the generated code having to compile
//! against them. A mismatch is a compile error in `OUT_DIR`, not a
//! silently wrong constant, so there is nothing for a test to assert.

use serde::Deserialize;
use std::{fmt::Write as _, path::PathBuf};

#[derive(Deserialize)]
struct BlackBoxLibrary {
    source: String,
    generated_by: String,
    /// A list of pairs rather than a map, so the emitted order matches the
    /// file's and a diff of the generated code reads like a diff of the
    /// library.
    modules: Vec<(String, Module)>,
}

#[derive(Deserialize)]
struct Module {
    ports: Vec<Port>,
    connectivity: Connectivity,
    note: Option<String>,
}

#[derive(Deserialize)]
struct Port {
    name: String,
    dir: Dir,
    width: usize,
    #[serde(default)]
    role: Role,
}

#[derive(Deserialize, PartialEq)]
enum Dir {
    Input,
    Output,
    Inout,
}

#[derive(Deserialize, Default, PartialEq)]
enum Role {
    #[default]
    Data,
    Clock,
    Reset,
}

#[derive(Deserialize)]
enum Connectivity {
    None,
    Opaque,
    Paths(Vec<(String, String)>),
}

fn main() {
    let libraries = [("xilinx-7series.ron", "xilinx_7series.rs", "xilinx")];
    for (input, output, module) in libraries {
        let src = PathBuf::from("primitives").join(input);
        println!("cargo:rerun-if-changed={}", src.display());
        let text = std::fs::read_to_string(&src)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", src.display()));
        let library: BlackBoxLibrary = ron::from_str(&text)
            .unwrap_or_else(|e| panic!("{} is not a valid library: {e}", src.display()));
        let generated = emit(&library, module, input);
        let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join(output);
        std::fs::write(&dest, generated)
            .unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
    }
}

fn emit(library: &BlackBoxLibrary, module: &str, input: &str) -> String {
    let mut out = String::new();
    writeln!(out, "// Generated by build.rs from primitives/{input}.").unwrap();
    writeln!(out, "// Do not edit; edit the library and rebuild.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Source: {}", library.source).unwrap();
    writeln!(out, "// Generated by: {}", library.generated_by).unwrap();
    writeln!(out, "#[allow(non_upper_case_globals)]").unwrap();
    writeln!(out, "pub mod {module} {{").unwrap();
    writeln!(
        out,
        "    use rhdl::core::circuit::blackbox_decl::{{\
         BlackBoxDecl, ConnectivityDecl, PortDecl, PortDir, PortRole}};"
    )
    .unwrap();

    for (name, m) in &library.modules {
        validate(name, m);
        writeln!(out, "    /// `{name}`, from the vendor library.").unwrap();
        if let Some(note) = &m.note {
            writeln!(out, "    ///").unwrap();
            for line in note.split_whitespace().collect::<Vec<_>>().chunks(12) {
                writeln!(out, "    /// {}", line.join(" ")).unwrap();
            }
        }
        writeln!(out, "    pub const {name}: BlackBoxDecl = BlackBoxDecl {{").unwrap();
        writeln!(out, "        module: {name:?},").unwrap();
        writeln!(out, "        ports: &[").unwrap();
        for p in &m.ports {
            let dir = match p.dir {
                Dir::Input => "Input",
                Dir::Output => "Output",
                Dir::Inout => "Inout",
            };
            let role = match p.role {
                Role::Data => "Data",
                Role::Clock => "Clock",
                Role::Reset => "Reset",
            };
            writeln!(
                out,
                "            PortDecl {{ name: {:?}, dir: PortDir::{dir}, \
                 width: {}, role: PortRole::{role} }},",
                p.name, p.width
            )
            .unwrap();
        }
        writeln!(out, "        ],").unwrap();
        match &m.connectivity {
            Connectivity::None => {
                writeln!(out, "        connectivity: ConnectivityDecl::None,").unwrap()
            }
            Connectivity::Opaque => {
                writeln!(out, "        connectivity: ConnectivityDecl::Opaque,").unwrap()
            }
            Connectivity::Paths(pairs) => {
                writeln!(out, "        connectivity: ConnectivityDecl::Paths(&[").unwrap();
                for (from, to) in pairs {
                    writeln!(out, "            ({from:?}, {to:?}),").unwrap();
                }
                writeln!(out, "        ]),").unwrap();
            }
        }
        match &m.note {
            Some(note) => writeln!(out, "        note: Some({note:?}),").unwrap(),
            None => writeln!(out, "        note: None,").unwrap(),
        }
        writeln!(out, "    }};").unwrap();
    }

    writeln!(out, "    /// Every declaration in this library.").unwrap();
    writeln!(out, "    pub const ALL: &[&BlackBoxDecl] = &[").unwrap();
    for (name, _) in &library.modules {
        writeln!(out, "        &{name},").unwrap();
    }
    writeln!(out, "    ];").unwrap();
    writeln!(out, "}}").unwrap();
    out
}

/// Reject a library entry that cannot be right, with the module named.
///
/// A build failure here is far better than a subtly wrong constant: these
/// are claims about silicon, and the analysis will believe them.
fn validate(name: &str, m: &Module) {
    if m.ports.is_empty() {
        panic!("{name}: no ports declared");
    }
    for p in &m.ports {
        if p.width == 0 {
            panic!("{name}: port {} has zero width", p.name);
        }
    }
    if let Connectivity::Paths(pairs) = &m.connectivity {
        for (from, to) in pairs {
            let source = m.ports.iter().find(|p| p.name == *from);
            let sink = m.ports.iter().find(|p| p.name == *to);
            match (source, sink) {
                (None, _) => panic!("{name}: path names input port {from}, which does not exist"),
                (_, None) => panic!("{name}: path names output port {to}, which does not exist"),
                (Some(s), Some(d)) => {
                    // A path must run from an input to an output. Getting
                    // this backwards in the file would otherwise produce a
                    // declaration that resolves and means nothing.
                    if s.dir != Dir::Input {
                        panic!("{name}: path source {from} is not an input");
                    }
                    if d.dir != Dir::Output {
                        panic!("{name}: path sink {to} is not an output");
                    }
                }
            }
        }
    }
}
