//! PS/2 keyboard encoder (FPGA emulates a PS/2 keyboard)
//!
//! Wraps [super::ps2_device_tx::Ps2DeviceTx] with the Scan Code
//! Set 2 byte-encoding logic so the host can drive the FPGA at
//! the higher level "send a make event for scancode X" / "send a
//! break event for scancode X (extended? yes/no)" without dealing
//! with the prefix bytes (E0 / F0) directly.
//!
//! The widget maintains a small 4-byte transmit queue so the host
//! can hand off the entire byte sequence (up to E0 F0 X for an
//! extended-key release = 3 bytes) and let the wire-layer
//! transmitter push them out at the protocol's 12.5 kHz rate
//! without further host attention until the queue drains.
//!
//! ## Make / break encoding
//!
//! - Single-byte make: `tx_byte` = scancode, push directly.
//! - Single-byte break: push `0xF0`, then scancode.
//! - Extended make: push `0xE0`, then scancode.
//! - Extended break: push `0xE0`, `0xF0`, then scancode.
//!
//! Pause/Break and PrintScreen aren't generated by this widget —
//! the host can manually push the multi-byte sequences via a
//! lower-level interface if needed (or use the underlying
//! `ps2_device_tx` directly).
//!
//! Composes [super::ps2_device_tx::Ps2DeviceTx].
//!
//! Here is the schematic symbol
#![doc = badascii_doc::badascii_formal!(r"
     +-------+Ps2KeyboardEncoder+--------+
     |                                   |
B<8> |                                   | bool
+--->| scancode             clk_oe       +-->
bool |                                   | bool
+--->| make                 data_oe      +-->
bool |                                   | bool
+--->| extended             tx_busy      +-->
bool |                                   | bool
+--->| send                 ready        +-->
bool |                                   |
+--->| clk_in                            |
     +-----------------------------------+
")]
//!
//!# Internals
//!
//! Three-state FSM (Idle, EnqueuingPrefix, Sending).  When `send`
//! pulses with non-zero `make` and/or `extended`, the widget
//! enqueues the prefix bytes (0, 1, or 2) followed by the
//! scancode itself, then sequences them through the wire-layer
//! TX one byte at a time, waiting for `tx_done` from each.
//!
//!# Parameters
//!
//! - `DIV_W` — bit width of the wire-layer half-period divisor
//!   (passed through to `Ps2DeviceTx`).
//!
//!# Example
//!
//!```
#![doc = include_str!("../../examples/ps2_keyboard_encoder.rs")]
//!```
//!
//! The trace below demonstrates the result.
#![doc = include_str!("../../doc/ps2_keyboard_encoder.md")]
//!
//! And the auto-generated FSM diagram:
#![doc = include_str!("../../doc/ps2_keyboard_encoder_fsm.md")]

use rhdl::prelude::*;

use super::ps2_device_tx::Ps2DeviceTx;
use crate::core::dff;

/// Encoder state machine — sequencing prefix bytes + scancode
/// through the wire-layer TX.
#[derive(PartialEq, Debug, Digital, Clone, Copy, Default, Fsm)]
pub enum KbdEncState {
    /// No event in flight; wait for `send` strobe.
    #[default]
    #[fsm_state(label = "idle")]
    Idle,
    /// Pushing E0 prefix (extended).
    #[fsm_state(label = "send E0")]
    SendE0,
    /// Pushing F0 prefix (break).
    #[fsm_state(label = "send F0")]
    SendF0,
    /// Pushing the scancode itself.
    #[fsm_state(label = "send scancode")]
    SendScancode,
    /// Waiting for the wire-layer TX to complete the current byte.
    #[fsm_state(label = "wait tx done")]
    WaitTxDone,
}

/// Bundled internal state for the PS/2 keyboard encoder
/// (CLAUDE.md §3.1).  The FSM-tagged enum stays in its own DFF;
/// the wire-layer TX is a real composed sub-circuit and stays
/// sibling-level.  Everything else lives here.
#[derive(PartialEq, Debug, Digital, Clone, Copy, Default)]
pub struct Ps2KeyboardEncoderExtras {
    pub scancode_q: Bits<8>,
    pub is_break: bool,
    pub is_extended: bool,
    pub sent_e0: bool,
    pub sent_f0: bool,
    pub pending_state: KbdEncState,
}

#[derive(Clone, Debug, Synchronous, SynchronousDQ, FsmWidget)]
#[rhdl(dq_no_prefix)]
#[fsm(state_field = "state", state_enum = KbdEncState, allow_implicit)]
/// PS/2 keyboard encoder (FPGA-as-keyboard).
pub struct Ps2KeyboardEncoder<const DIV_W: usize>
where
    rhdl::bits::W<DIV_W>: BitWidth,
{
    state: dff::DFF<KbdEncState>,
    extras: dff::DFF<Ps2KeyboardEncoderExtras>,
    /// Wire-layer TX (composed sub-circuit).
    tx: Ps2DeviceTx<DIV_W>,
}

impl<const DIV_W: usize> Ps2KeyboardEncoder<DIV_W>
where
    rhdl::bits::W<DIV_W>: BitWidth,
{
    /// Create with the given wire-layer half-period.
    pub fn new(half_period: Bits<DIV_W>) -> Self {
        Self {
            state: dff::DFF::default(),
            extras: dff::DFF::default(),
            tx: Ps2DeviceTx::new(half_period),
        }
    }
}

#[derive(PartialEq, Debug, Digital, Clone, Copy)]
/// Inputs to [Ps2KeyboardEncoder].
pub struct In {
    /// Scancode to send.
    pub scancode: Bits<8>,
    /// True for a make event (key press), false for break (release).
    pub make: bool,
    /// True for an extended-key event (E0 prefix).
    pub extended: bool,
    /// Pulse for one cycle to start the sequence.  Ignored unless ready.
    pub send: bool,
    /// Sampled CLK input from the wire (for inhibit detection).
    pub clk_in: bool,
}

#[derive(PartialEq, Debug, Digital, Clone, Copy)]
/// Outputs from [Ps2KeyboardEncoder].
pub struct Out {
    /// Drive CLK low when true.
    pub clk_oe: bool,
    /// Drive DATA low when true.
    pub data_oe: bool,
    /// True while a multi-byte sequence is in flight.
    pub tx_busy: bool,
    /// True when ready to accept a new `send` strobe.
    pub ready: bool,
}

impl<const DIV_W: usize> SynchronousIO for Ps2KeyboardEncoder<DIV_W>
where
    rhdl::bits::W<DIV_W>: BitWidth,
{
    type I = In;
    type O = Out;
    type Kernel = ps2_keyboard_encoder<DIV_W>;
}

#[kernel]
/// Kernel for [Ps2KeyboardEncoder].
pub fn ps2_keyboard_encoder<const DIV_W: usize>(
    cr: ClockReset,
    i: In,
    q: Q<DIV_W>,
) -> (Out, D<DIV_W>)
where
    rhdl::bits::W<DIV_W>: BitWidth,
{
    let mut d = D::<DIV_W>::dont_care();
    d.state = q.state;
    let mut next = q.extras;

    let mut tx_in = super::ps2_device_tx::In {
        tx_byte: bits::<8>(0),
        tx_strobe: false,
        clk_in: i.clk_in,
    };

    match q.state {
        KbdEncState::Idle => {
            if i.send {
                next.scancode_q = i.scancode;
                next.is_break = !i.make;
                next.is_extended = i.extended;
                next.sent_e0 = false;
                next.sent_f0 = false;
                if i.extended {
                    d.state = KbdEncState::SendE0;
                } else if !i.make {
                    d.state = KbdEncState::SendF0;
                } else {
                    d.state = KbdEncState::SendScancode;
                }
            }
        }
        KbdEncState::SendE0 => {
            tx_in.tx_byte = bits::<8>(0xE0);
            tx_in.tx_strobe = true;
            next.sent_e0 = true;
            next.pending_state = if q.extras.is_break {
                KbdEncState::SendF0
            } else {
                KbdEncState::SendScancode
            };
            d.state = KbdEncState::WaitTxDone;
        }
        KbdEncState::SendF0 => {
            tx_in.tx_byte = bits::<8>(0xF0);
            tx_in.tx_strobe = true;
            next.sent_f0 = true;
            next.pending_state = KbdEncState::SendScancode;
            d.state = KbdEncState::WaitTxDone;
        }
        KbdEncState::SendScancode => {
            tx_in.tx_byte = q.extras.scancode_q;
            tx_in.tx_strobe = true;
            next.pending_state = KbdEncState::Idle;
            d.state = KbdEncState::WaitTxDone;
        }
        KbdEncState::WaitTxDone => {
            if q.tx.tx_done {
                d.state = q.extras.pending_state;
            }
        }
    }

    d.tx = tx_in;

    if cr.reset.any() {
        d.state = KbdEncState::Idle;
        next = Ps2KeyboardEncoderExtras::default();
    }

    d.extras = next;

    let mut o = Out::dont_care();
    o.clk_oe = q.tx.clk_oe;
    o.data_oe = q.tx.data_oe;
    o.tx_busy = q.state != KbdEncState::Idle;
    o.ready = q.state == KbdEncState::Idle;
    (o, d)
}

#[cfg(test)]
mod tests {
    use super::*;
    use expect_test::expect;
    use std::path::PathBuf;

    fn idle_in() -> In {
        In {
            scancode: bits(0),
            make: false,
            extended: false,
            send: false,
            clk_in: true,
        }
    }

    fn send_in(scancode: u8, make: bool, extended: bool) -> In {
        In {
            scancode: bits::<8>(scancode as u128),
            make,
            extended,
            send: true,
            clk_in: true,
        }
    }

    #[test]
    fn test_send_strobe_starts_busy() -> miette::Result<()> {
        let mut stream_in = vec![idle_in(); 2];
        stream_in.push(send_in(0x1C, true, false));
        for _ in 0..400 {
            stream_in.push(idle_in());
        }
        let stream = stream_in.into_iter().with_reset(2).clock_pos_edge(100);
        let uut = Ps2KeyboardEncoder::<8>::new(bits(4));
        let outputs: Vec<_> = uut
            .run(stream)
            .synchronous_sample()
            .filter(|s| !s.input.0.reset.any())
            .collect();
        assert!(outputs.iter().any(|s| s.output.tx_busy));
        Ok(())
    }

    #[test]
    fn test_make_event_one_byte_sent() -> miette::Result<()> {
        // Verify that for a make event, the wire-layer is strobed
        // exactly once (one byte: the scancode).
        let mut stream_in = vec![idle_in(); 2];
        stream_in.push(send_in(0x1C, true, false));
        for _ in 0..400 {
            stream_in.push(idle_in());
        }
        let stream = stream_in.into_iter().with_reset(2).clock_pos_edge(100);
        let uut = Ps2KeyboardEncoder::<8>::new(bits(4));
        let outputs: Vec<_> = uut
            .run(stream)
            .synchronous_sample()
            .filter(|s| !s.input.0.reset.any())
            .collect();
        // Eventually returns to Idle.
        let last_busy_cycle = outputs.iter().enumerate().filter(|(_, s)| s.output.tx_busy).map(|(i, _)| i).max().unwrap_or(0);
        let last_cycle = outputs.len() - 1;
        assert!(last_busy_cycle < last_cycle, "encoder never returned to idle");
        Ok(())
    }

    #[test]
    fn test_vlog_generation() -> miette::Result<()> {
        let uut = Ps2KeyboardEncoder::<13>::new(bits(4000));
        let desc = uut.descriptor("top".into())?;
        let hdl = desc.hdl()?.modules.pretty();
        assert!(hdl.len() > 1000, "HDL length {}", hdl.len());
        Ok(())
    }

    #[test]
    fn test_ps2_keyboard_encoder_hdl_works() -> miette::Result<()> {
        let mut stream_in = vec![idle_in(); 2];
        stream_in.push(send_in(0x1C, true, false));
        for _ in 0..40 {
            stream_in.push(idle_in());
        }
        let stream = stream_in.into_iter().with_reset(2).clock_pos_edge(100);
        let uut = Ps2KeyboardEncoder::<8>::new(bits(4));
        let test_bench = uut.run(stream).collect::<SynchronousTestBench<_, _>>();
        let tm = test_bench.rtl(&uut, &Default::default())?;
        tm.run_iverilog()?;
        Ok(())
    }

    #[test]
    fn test_ps2_keyboard_encoder_trace() -> miette::Result<()> {
        let mut stream_in = vec![idle_in(); 2];
        stream_in.push(send_in(0x1C, false, true));
        for _ in 0..400 {
            stream_in.push(idle_in());
        }
        let stream = stream_in.into_iter().with_reset(2).clock_pos_edge(100);
        let uut = Ps2KeyboardEncoder::<8>::new(bits(4));
        let vcd = uut.run(stream).collect::<VcdFile>();
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("vcd")
            .join("ps2_keyboard_encoder");
        std::fs::create_dir_all(&root).unwrap();
        let _ = vcd.dump_to_file(root.join("ps2_keyboard_encoder.vcd")).unwrap();
        let _ = expect![[r#""#]];
        Ok(())
    }

    #[test]
    fn test_fsm_descriptor_round_trip() {
        let desc = Ps2KeyboardEncoder::<13>::fsm_descriptor();
        assert_eq!(desc.widget_name, "Ps2KeyboardEncoder");
        assert_eq!(desc.variants().len(), 5);
    }
}
